import { registerAs } from '@nestjs/config';

export const appConfig = registerAs('app', () => ({
  env: process.env.NODE_ENV || 'local',
  clientId: process.env.MYRROR_CLIENT_ID,
  clientSecret: process.env.MYRROR_SECRET,
  apiUrl: process.env.MYRROR_API || 'https://api.myrror.com/v1',
  timeout: process.env.MYRROR_TIMEOUT || 60 * 60 * 1000,
  isManualWebhookMode: process.env.MYRROR_IS_MANUAL_WEBHOOK_MODE,
  retryTime: process.env.MYRROR_RETRY_TIME || 10000,
  repository: process.env.MYRROR_REPOSITORY,
  rootNamespace: process.env.MYRROR_ROOT_NAMESPACE,
  branch: process.env.MYRROR_BRANCH,
  commit: process.env.MYRROR_COMMIT,
  commitAuthor: process.env.MYRROR_COMMIT_AUTHOR,
  commitMessage: process.env.MYRROR_COMMIT_MESSAGE,
  commitTitle: process.env.MYRROR_COMMIT_TITLE,
  commitTimestamp: process.env.MYRROR_COMMIT_TIMESTAMP,
  scmType: process.env.MYRROR_SCM_TYPE,
  orgId: process.env.MYRROR_ORG_ID,
  jobToken: process.env.MYRROR_JOB_TOKEN,
  projectId: process.env.MYRROR_PROJECT_ID,
  projectUrl: process.env.MYRROR_PROJECT_URL,
  mergeRequestId: process.env.MYRROR_MERGE_REQUEST_ID,
  mergeRequestIid: process.env.MYRROR_MERGE_REQUEST_IID,
  mergeRequestState: process.env.MYRROR_MERGE_REQUEST_STATE,
  mergeRequestTitle: process.env.MYRROR_MERGE_REQUEST_TITLE,
  mergeRequestProjectUrl: process.env.MYRROR_MERGE_REQUEST_PROJECT_URL,
  mergeRequestCreatedAt: process.env.MYRROR_MERGE_REQUEST_CREATED_AT,
  mergeRequestUpdatedAt: process.env.MYRROR_MERGE_REQUEST_UPDATED_AT,
  mergeRequestSourceBranch: process.env.MYRROR_MERGE_REQUEST_SOURCE_BRANCH,
  mergeRequestTargetBranch: process.env.MYRROR_MERGE_REQUEST_TARGET_BRANCH,
}));
