myrror-scan:
  stage: test
  image: myrrorsecurity/myrror-cli:latest
  before_script:
    - MYRROR_REPOSITORY=$CI_PROJECT_PATH
    - MYRROR_ROOT_NAMESPACE=$CI_PROJECT_ROOT_NAMESPACE
    - apt-get -qq update
    - apt-get install -y jq
    - |
      if [ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]; then
        MR_DETAILS=$(curl --header "PRIVATE-TOKEN: $ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID")
        MYRROR_MERGE_REQUEST_STATE=$(echo "$MR_DETAILS" | jq -r ".state")
        MYRROR_MERGE_REQUEST_CREATED_AT=$(echo "$MR_DETAILS" | jq -r ".created_at")
        MYRROR_MERGE_REQUEST_UPDATED_AT=$(echo "$MR_DETAILS" | jq -r ".updated_at")
        export MYRROR_MERGE_REQUEST_STATE
        export MYRROR_MERGE_REQUEST_CREATED_AT
        export MYRROR_MERGE_REQUEST_UPDATED_AT
      fi
  script:
    - node /usr/src/app/dist/main status -r $MYRROR_REPOSITORY -b $MYRROR_BRANCH -c $MYRROR_COMMIT -rns $MYRROR_ROOT_NAMESPACE
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    MYRROR_SCM_TYPE: gitlab
    MYRROR_BRANCH: $CI_COMMIT_REF_NAME
    MYRROR_COMMIT: $CI_COMMIT_SHA
    MYRROR_COMMIT_AUTHOR: $CI_COMMIT_AUTHOR
    MYRROR_COMMIT_MESSAGE: $CI_COMMIT_MESSAGE
    MYRROR_COMMIT_TIMESTAMP: $CI_COMMIT_TIMESTAMP
    MYRROR_COMMIT_TITLE: $CI_COMMIT_TITLE
    MYRROR_MERGE_REQUEST_ID: $CI_MERGE_REQUEST_ID
    MYRROR_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    MYRROR_MERGE_REQUEST_TITLE: $CI_MERGE_REQUEST_TITLE
    MYRROR_MERGE_REQUEST_PROJECT_URL: $CI_MERGE_REQUEST_PROJECT_URL
    MYRROR_MERGE_REQUEST_SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    MYRROR_MERGE_REQUEST_TARGET_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME

