myrror-scan:
  stage: test
  image: myrrorsecurity/myrror-cli:latest
  before_script:
    - MYRROR_REPOSITORY=$CI_PROJECT_PATH
    - MYRROR_ROOT_NAMESPACE=$CI_PROJECT_ROOT_NAMESPACE
  script:
    - node /usr/src/app/dist/main status -r $MYRROR_REPOSITORY -b $MYRROR_BRANCH -c $MYRROR_COMMIT -rns $MYRROR_ROOT_NAMESPACE -pri $MYRROR_PULL_REQUEST_IID -roi $MYRROR_REPO_ORIGIN_ID -esw $MYRROR_ENABLED_SYNTHETIC_WEBHOOKS
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    MYRROR_BRANCH: $CI_COMMIT_REF_NAME
    MYRROR_COMMIT: $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    MYRROR_PULL_REQUEST_IID: $CI_MERGE_REQUEST_IID
    MYRROR_REPO_ORIGIN_ID: $CI_PROJECT_ID
    MYRROR_ENABLED_SYNTHETIC_WEBHOOKS: 'true'
