pipelines:
  default:
    - step:
        name: Myrror Scan check for PR to YOUR_MAIN_BRANCH
        image: myrrorsecurity/myrror-cli:latest
        caches:
          - node
        script:
          - echo "Installing axios..."
          - npm install axios
          - echo "Checking for open pull requests from $BITBUCKET_BRANCH to YOUR_MAIN_BRANCH"
          - |
            node -e "
              const axios = require('axios');

              (async () => {
                try {
                  const response = await axios.get(
                    'https://api.bitbucket.org/2.0/repositories/$BITBUCKET_REPO_FULL_NAME/pullrequests', {
                    headers: {
                      'Authorization': 'Bearer $BITBUCKET_OAUTH_TOKEN'
                    },
                    params: {
                      q: 'source.branch.name=\"$BITBUCKET_BRANCH\" AND destination.branch.name=\"YOUR_MAIN_BRANCH\" AND state=\"OPEN\"'
                    }
                  });
                  const data = response.data;
                  const prCount = data.values ? data.values.length : 0;
                  console.log('Number of open PRs from $BITBUCKET_BRANCH to YOUR_MAIN_BRANCH:', prCount);
                  
                  if (prCount === 0) {
                    console.log('No open pull request from $BITBUCKET_BRANCH to YOUR_MAIN_BRANCH. Skipping the pipeline.');
                    process.exit(0); // Exits the pipeline successfully
                  } else {
                    console.log('Open pull request found from $BITBUCKET_BRANCH to YOUR_MAIN_BRANCH. Proceeding with the pipeline.');
                  }
                } catch (error) {
                  console.log('error: ', error);
                  if (error.response) {
                    console.log('Error fetching PR data:', error.response.status, error.response.statusText);
                  } else {
                    console.log('Error:', error.message);
                  }
                  process.exit(1); // Fails the pipeline in case of error
                }
              })();
            "
          - export MYRROR_REPOSITORY=$BITBUCKET_REPO_SLUG
          - export MYRROR_BRANCH=$BITBUCKET_BRANCH
          - export MYRROR_COMMIT=$BITBUCKET_COMMIT
          - export MYRROR_CLIENT_ID=$MYRROR_CLIENT_ID
          - export MYRROR_SECRET=$MYRROR_SECRET
          - export MYRROR_API="https://api.ls.blindspot-security.com/v1"
          - node /usr/src/app/dist/main status -r $MYRROR_REPOSITORY -b $MYRROR_BRANCH -c $MYRROR_COMMIT
  pull-requests:
    YOUR_MAIN_BRANCH:
      - step:
          name: Myrror Scan on PR to YOUR_MAIN_BRANCH
          image: myrrorsecurity/myrror-cli:latest
          caches:
            - node
          script:
            - echo "Running Myrror scan for PR to YOUR_MAIN_BRANCH"
            - export MYRROR_REPOSITORY=$BITBUCKET_REPO_SLUG
            - export MYRROR_BRANCH=$BITBUCKET_BRANCH
            - export MYRROR_COMMIT=$BITBUCKET_COMMIT
            - export MYRROR_CLIENT_ID=$MYRROR_CLIENT_ID
            - export MYRROR_SECRET=$MYRROR_SECRET
            - export MYRROR_API="https://api.ls.blindspot-security.com/v1"
            - node /usr/src/app/dist/main status -r $MYRROR_REPOSITORY -b $MYRROR_BRANCH -c $MYRROR_COMMIT
